import { NextResponse } from "next/server";
import type { NextRequest } from "next/server";
import { jwtVerify } from "jose";

// Build a Uint8Array key from your env secret (must match where you sign)
const secret = new TextEncoder().encode(process.env.JWT_SECRET || "devsecret");

export async function middleware(req: NextRequest) {
  // The matcher below already ensures we only run on the routes we care about,
  // so no need to re-check prefixes here.

  const token = req.cookies.get("session")?.value;
  if (!token) {
    const url = new URL("/signin", req.url);
    url.searchParams.set("next", req.nextUrl.pathname);
    return NextResponse.redirect(url);
  }

  try {
    // Verify token. Throws if invalid/expired.
    await jwtVerify(token, secret);
    return NextResponse.next();
  } catch {
    const url = new URL("/signin", req.url);
    url.searchParams.set("next", req.nextUrl.pathname);
    return NextResponse.redirect(url);
  }
}

// Protect the (admin) route group (URL paths generated by that group).
// Remember: route group name with parentheses does NOT appear in the URL,
// but Next's matcher understands it.
export const config = {
  matcher: ["/(admin)(.*)"],
};
